create table users(
id int not null auto_increment primary key,
sex varchar(255),
name varchar(255),
picture varchar(255),
create_date datetime,
skl_direction int,
skl_presentation int,
skl_research int,
skl_contentsmaking int,
skl_design int,
d_art int,
d_illust int,
d_ellegant int,
d_cute int,
d_cool int,
d_simple int,
d_natural int,
d_pop int,
d_retro int,
d_japanese int,
skl_ios int,
skl_android int,
skl_windows8 int,
skl_html int,
skl_css int,
skl_javascript int,
skl_python int,
skl_ruby int,
skl_php int,
skl_java int,
skl_perl int,
skl_c int,
skl_cpp int,
skl_wordpress int,
pr_logical int,
pr_indoor int,
pr_aggressive int
);


insert into users (id, sex, name, picture, create_date, skl_direction, skl_presentation, skl_research, skl_contentsmaking, skl_design, d_art, d_illust, d_ellegant, d_cute, d_cool, d_simple, d_natural, d_pop, d_retro, d_japanese, skl_ios, skl_android, skl_windows8, skl_html, skl_css, skl_javascript, skl_python, skl_ruby, skl_php, skl_java, skl_perl, skl_c, skl_cpp, skl_wordpress, pr_logical, pr_indoor, pr_aggressive) values (1, "f", "foo", "pic", "98-12-31 11:30:45", 5, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3);
